# Metode Cluster Hirarki

## Data
```{r Load_data,warning=FALSE, tidy=FALSE}
library (readr)
urlfile = "https://raw.githubusercontent.com/dedenistiawan/Dataset/main/Basis%20Data%20Terpadu%20Jateng.csv"

data<-read.csv(url(urlfile), row.names = "Kabupaten")
```

```{r nice-tab, tidy=FALSE}
knitr::kable(
  head(data, 10), caption = 'Basis Data Terpadu Jawa Tengah',
  booktabs = TRUE)
```

```{r}
# Standardize the data
df <- scale(data)
```


```{r}
# Compute the dissimilarity matrix
# df = the standardized data
res.dist <- dist(df, method = "euclidean")
```

```{r}
as.matrix(res.dist)[1:5, 1:5]
```

```{r}
res.hc <- hclust(d =res.dist, method = "ward.D2")
```

```{r warning=FALSE}
# cex: label size
library("factoextra")
library(ggplot2)
fviz_dend(res.hc, cex = 0.5)
```


```{r}
# Cut tree into 2 groups
grp <- cutree(res.hc, k =2)
head(grp, n =2)
```
```{r}
# Number of members in each cluster
table(grp)
```
```{r}
# Cut in 2 groups and color by groups
fviz_dend(res.hc, k =2, # Cut in four groups
          cex = 0.5, # label size
          k_colors = c("#E7B800", "#FC4E07"),
          color_labels_by_k = TRUE, # color labels by groups
          rect = TRUE # Add rectangle around groups)
          )
```

```{r}
fviz_cluster(list(data = df, cluster = grp),
palette = c("#E7B800", "#FC4E07"),
ellipse.type = "convex", # Concentration ellipse
repel = TRUE, # Avoid label overplotting (slow)
show.clust.cent = FALSE, ggtheme = theme_minimal())
```

## Comparing dendrograms
```{r warning=FALSE}
library(dendextend)
# Compute distance matrix
res.dist <- dist(df, method = "euclidean")

# Compute 2 hierarchical clusterings
hc1 <- hclust(res.dist, method = "average")
hc2 <- hclust(res.dist, method = "ward.D2")

# Create two dendrograms
dend1 <- as.dendrogram (hc1)
dend2 <- as.dendrogram (hc2)

# Create a list to hold dendrograms
dend_list <- dendlist(dend1, dend2)
```

```{r}
tanglegram(dend1, dend2)
```
```{r}
tanglegram(dend1, dend2,
highlight_distinct_edges = FALSE, # Turn-off dashed lines
common_subtrees_color_lines = FALSE, # Turn-off line colors
common_subtrees_color_branches = TRUE, # Color common branches
main = paste("entanglement =", round(entanglement(dend_list), 2))
)
```
```{r}
# Create multiple dendrograms by chaining
dend1 <- df %>% dist %>% hclust("complete") %>%as.dendrogram
dend2 <- df %>% dist %>% hclust("single") %>%as.dendrogram
dend3 <- df %>% dist %>% hclust("average") %>%as.dendrogram
dend4 <- df %>% dist %>% hclust("centroid") %>%as.dendrogram
# Compute correlation matrix
dend_list <- dendlist("Complete" = dend1, "Single" = dend2,
"Average" = dend3, "Centroid" = dend4)
cors <- cor.dendlist(dend_list)
# Print correlation matrix
round(cors, 2)
```
```{r}
# Visualize the correlation matrix using corrplot package
library(corrplot)
corrplot(cors, "pie", "lower")
```
```{r}
# Compute distances and hierarchical clustering
dd <- dist(scale(data), method = "euclidean")
hc <- hclust(dd, method = "ward.D2")
```

```{r}
library(factoextra)
fviz_dend(hc, cex = 0.5)
```
```{r}
fviz_dend(hc, cex = 0.5,
main = "Dendrogram - ward.D2",
xlab = "Objects", ylab = "Distance", sub = "")
```

```{r}
fviz_dend(hc, cex = 0.5, horiz = TRUE)
```
```{r}
fviz_dend(hc, k =2, # Cut in four groups
cex = 0.5, # label size
k_colors = c("#E7B800", "#FC4E07"),
color_labels_by_k = TRUE, # color labels by groups
rect = TRUE, # Add rectangle around groups
rect_border = c("#E7B800", "#FC4E07"),
rect_fill = TRUE)
```
```{r}
fviz_dend(hc, k =2,
# Cut in four groups
cex = 0.5,
# label size
k_colors = c("#E7B800", "#FC4E07"),
color_labels_by_k = TRUE, # color labels by groups
ggtheme = theme_gray()
# Change theme
)
```
```{r}
fviz_dend(hc, cex = 0.5, k =2, # Cut in four groups
k_colors = "jco")
```
```{r}
fviz_dend(hc, k =2, cex = 0.4, horiz = TRUE, k_colors = "jco",
rect = TRUE, rect_border = "jco", rect_fill = TRUE)
```
```{r}
fviz_dend(hc, cex = 0.5, k =2,
k_colors = "jco", type = "circular")
```
```{r}
require("igraph")
fviz_dend(hc, k =2, k_colors = "jco",
type = "phylogenic", repel = TRUE)
```
```{r}
require("igraph")
fviz_dend(hc, k =2, # Cut in four groups
k_colors = "jco",
type = "phylogenic", repel = TRUE,
phylo_layout = "layout.gem")
```

